### PR TITLE
Assignment 1 Submission

### PR DESCRIPTION
**Pull request by RamMohanMadhamanchi**

### CODE REVIEW

**Comment by RamMohanMadhamanchi** [comment]
screenshot1

**Comment by saikiransathpadi** [comment]
correct, but layout should not be scrollable it should be of full width

**Review by saikiransathpadi — APPROVED** [review]

**Comment by Arvaaz** [comment]
All good but Layout should be in a single page...
increase the text size in list..

**Comment by RamMohanMadhamanchi** [comment]
screenshot1

**Pull request merged**
